### Spring properties
# Service registers under this name
spring:
  application:
    name: ORDER
  h2:
    console:
      enabled: true

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8080/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 8087
  #context-path: /catalog

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false

